### PR TITLE
Initial commit of React example.

### PR DESCRIPTION
**Pull request by awong-dev**

### CODE REVIEW

**Comment by jeffmaher** [comment]
I'll be offsite tomorrow, but happy to review on Thursday. If you need this in sooner, feel free to delegate to another dev on the team.

**Comment by awong-dev** [comment]
No rush. However, this is actually pretty awesome. I got hot-reload working :D.

**Comment by jeffmaher** [comment]
Nice! :smile:

**Comment by jeffmaher** [comment]
@shanear : If you have any bandwidth today could you review too? I'm probably going to learn a lot by reviewing this on Thursday, but you're the better one to make recommendations.

**Comment by shanear** [comment]
Looking good :+1: 

one thing I'm noticing is that the linter isn't running in travis, which seems problematic.

**Comment by shanear** [comment]
I'm also wondering if we'll eventually want a task manager like grunt/gulp/broccoli to help orchestrate build/lint/test things. Seems like good ole' npm is working for now though!

**Comment by awong-dev** [comment]
I was hoping to keep grunt/gulp/broccoli out of it since webpack is handling so much of the dependency logic.

Open the idea, but waiting to see it being needed first.  One less tool is one bit better...

I will fix the lint run in travis. Good catch.

**Comment by awong-dev** [comment]
@shanear PTAL.

Hoping i can get an LGTM :)

**Comment by shanear** [comment]
Agreed. :+1: 

LGTM

**Pull request merged**
